### ISSUE TITLE
Outdated examples in modelling_context and intervention_variables

### ISSUE THREAD

**Issue by carlos-saez** [rjdverse/rjd3toolkit#49]
In the examples for the functions `modelling_context` and `intervention_variables` the following lines of code appear (commented):
```
# customize a default specification
# init_spec <- rjd3x13::spec_x13("RSA5c")
# new_spec<- add_usrdefvar(init_spec,id = "reg1.iv1", regeffect="Trend")
# modelling context is needed for the estimation phase
# sa_x13<- rjd3x13::x13(ABS$X0.2.09.10.M, new_spec, context = my_context)
```
However, this code doesn't work with the present version of the R packages.  `rjd3x13::spec_x13` gives a "deprecated" warning, while  `new_spec<- add_usrdefvar(init_spec,id = "reg1.iv1", regeffect="Trend")` gives an error since there is no `id` argument in the present version of `add_usrdefvar`.

Also, the examples in `add_usrdefvar` use the deprecated function `rjd3x13::spec_x13` instead of the new version `rjd3x13::x13_spec`.

**Comment by annasmyk** [comment]
Hi Carlos, 
thanks for pointing this out.  We'll solve this this week.
Anna
